"""Tripwire for accidental resurrection of deliberately deleted paths.

These paths were deleted on purpose. Deleted is not banned: this test only catches a
path coming back by accident, most often through a merge of an old lineage. If a
revival is intentional, delete the path's row below.
"""
from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]

# Keep the reason beside each path.  A failure should tell the next maintainer
# which decision the returning path would undo.
RETIRED_PATHS = (
    ('api/webui/routes/push.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/routes/push_validation.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/routes/work.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/routes/roster.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/routes/roster_changes.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/routes/roster_helpers.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/routes/roster_updates.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/roster_mcp.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/static/push', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/static/course_expert', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/static/roster', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/static/roster.js', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/static/roster_workbench.css', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/static/course_info.js', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/static/write_review.js', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/static/app_context.js', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/templates/course_expert.html', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/templates/course.html', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/templates/ai_expert.html', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/webui/templates/roster.html', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/roster_context.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/student_packet.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/portfolio.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/portfolio_service.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/report_local_reads.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('api/submission_transport.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('docs/reference/course-expert-module-map.md', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/core', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/spec_engine', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/rendering/physical', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/rendering/correction_doc', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/rendering/forge/printable.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/importers.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/utils/json_lint.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/validation/point_calculator.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/validation/answer_balancer.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/packaging', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/packagers/physical_handler.py', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),
    ('engine/docs', '(none)', 'Agentic-center batch 3: console charter and no generated printables'),

    ("api/canvas.py", "(none)", "Close the standalone QuizForge Canvas transport"),
    ("CLAUDE.md", "bfe1877", "Add TAForge and canonical agent guidance"),
    (
        "api/default_docs/AI Authoring/NoteForge_Base.md",
        "(none)",
        "old-lineage only; NoteForge leaves no other trace on this lineage",
    ),
    ("api/downloader.py", "f8a8f22", "Retire duplicate Download Work workflow"),
    ("api/tests/test_downloader.py", "f8a8f22", "Retire duplicate Download Work workflow"),
    ("api/tests/test_noteforge_physical_routes.py", "926b4f2", "Modularize live-fire workflows"),
    ("api/webui/activity.py", "6110c48", "Complete 0.75beta local hardening and MCP support"),
    ("api/webui/runner.py", "(none)", "Remove quiz planner subprocess transport"),
    ("api/webui/config.py", "87b2a80", "Refactor web UI modules and document next slices"),
    ("api/webui/push_service.py", "cbd6738", "Cleanup legacy Course Expert standalone push surfaces"),
    ("api/webui/static/style.css", "1c2d9f7", "Complete WebUI presentation migration"),
    ("api/webui/templates/_course_picker.html", "1c2d9f7", "Complete WebUI presentation migration"),
    ("api/webui/templates/download_work.html", "cbd6738", "Cleanup legacy Course Expert standalone push surfaces"),
    ("api/webui/templates/feedback_expert.html", "f53394e", "Complete local-first Luna 5-7 surfaces"),
    ("api/webui/templates/name_manager.html", "1c2d9f7", "Complete WebUI presentation migration"),
    ("api/webui/templates/push_assignment.html", "cbd6738", "Cleanup legacy Course Expert standalone push surfaces"),
    ("api/webui/templates/push_note.html", "926b4f2", "Modularize live-fire workflows"),
    ("api/webui/templates/push_page.html", "cbd6738", "Cleanup legacy Course Expert standalone push surfaces"),
    ("api/webui/templates/push_quick.html", "cbd6738", "Cleanup legacy Course Expert standalone push surfaces"),
    ("api/webui/templates/push_quiz.html", "cbd6738", "Cleanup legacy Course Expert standalone push surfaces"),
    ("api/webui/templates/push_rubric.html", "cbd6738", "Cleanup legacy Course Expert standalone push surfaces"),
    ("api/default_docs/AI Authoring/Author a SmartDeck (SlideForge).txt", "(none)", "Retire the classroom-display authoring contract"),
    ("api/default_docs/SmartDecks/Teacher Schedule.template.json", "(none)", "Move the teacher schedule seed into Calendars"),
    ("api/seating_constraints.py", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/seating_grouping.py", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/seating_state.py", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/platform_services/config/seating.py", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/operation_ledger/adapters/seating_group_set.py", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/webui/routes/seating.py", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/webui/templates/seating.html", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/webui/static/seating.css", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/webui/static/seating.js", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/tests/test_seating_constraints.py", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/tests/test_seating_grouping.py", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/tests/test_seating_state.py", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/tests/test_seating_routes.py", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/tests/test_seating_group_export.py", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("docs/reference/seating-feature-overview.md", "(none)", "Retire Seating; only ever useful via MCP and that did not pan out"),
    ("api/smartdeck_feeds.py", "(none)", "Retire dead classroom-display feed projections"),
    ("api/tests/test_smartdeck_routes.py", "(none)", "Retire the classroom-display management routes"),
    ("api/tests/test_smartdeck_display.py", "(none)", "Retire the classroom-display projector routes"),
    ("api/tests/test_smartdeck_feeds.py", "(none)", "Retire dead classroom-display feed tests"),
    ("api/tests/test_deck_store.py", "(none)", "Retire classroom-display storage"),
    ("api/tests/test_sf.py", "(none)", "Retire the classroom-display format validator"),
    ("api/webui/routes/smartdeck.py", "(none)", "Retire the classroom-display routes"),
    ("api/webui/deck_store.py", "(none)", "Retire classroom-display storage"),
    ("api/webui/sf.py", "(none)", "Retire the classroom-display format validator"),
    ("api/webui/templates/smartdeck.html", "(none)", "Retire the classroom-display management UI"),
    ("api/webui/templates/smartdeck_display.html", "(none)", "Retire the classroom-display projector UI"),
    ("api/webui/static/smartdeck/smartdeck.js", "(none)", "Retire the classroom-display management UI"),
    ("api/webui/static/smartdeck/smartdeck.css", "(none)", "Retire the classroom-display management UI"),
    ("api/webui/static/smartdeck/slide_select.js", "(none)", "Retire the classroom-display projector UI"),
    ("api/webui/static/smartdeck/display.js", "(none)", "Retire the classroom-display projector UI"),
    ("api/webui/static/smartdeck/display.css", "(none)", "Retire the classroom-display projector UI"),
    ("api/tests/smartdeck/widget_lifecycle.test.mjs", "(none)", "Retire classroom-display browser tests"),
    ("api/tests/smartdeck/test_display_js.py", "(none)", "Retire classroom-display browser tests"),
    ("api/tests/smartdeck/slide_select.test.mjs", "(none)", "Retire classroom-display browser tests"),
    ("docs/reference/smartdeck-module-map.md", "(none)", "Retire the classroom-display route card"),
    ("api/webui/routes/panels.py", "(none)", "Retire the Panels classroom-display routes in Glass Slice 6"),
    ("api/webui/glass.py", "(none)", "Remove the classroom display entirely: too little value for the upkeep"),
    ("api/webui/glass_board.py", "(none)", "Remove the classroom display entirely: too little value for the upkeep"),
    ("api/webui/glass_class.py", "(none)", "Remove the classroom display entirely: too little value for the upkeep"),
    ("api/webui/glass_data.py", "(none)", "Remove the classroom display entirely: too little value for the upkeep"),
    ("api/webui/routes/glass.py", "(none)", "Remove the classroom display entirely: too little value for the upkeep"),
    ("api/webui/templates/glass.html", "(none)", "Remove the classroom display entirely: too little value for the upkeep"),
    ("api/webui/static/pages/glass.css", "(none)", "Remove the classroom display entirely: too little value for the upkeep"),
    ("api/webui/static/pages/glass.js", "(none)", "Remove the classroom display entirely: too little value for the upkeep"),
    ("api/panel_themes.py", "(none)", "Remove the Panel theme system with the display it themed"),
    ("tools/design_theme_studio.py", "(none)", "Remove the Panel theme system with the display it themed"),
    ("tools/manifests/design-theme-studio.json", "(none)", "Remove the Panel theme system with the display it themed"),
    ("api/audience.py", "(none)", "Classroom-facing/teacher-facing split had no consumer once the display went"),
    ("docs/contracts/classroom-facing-data-contract.md", "(none)", "Contract for the removed classroom display"),
    ("docs/reference/Architecture Narrative - Scenes.md", "(none)", "Superseded narrative for the removed display, under its oldest name"),
    ("api/webui/panel_data.py", "(none)", "Move Glass projections out of the retired Panels module"),
    ("api/webui/templates/panels.html", "(none)", "Retire the Panels console"),
    ("api/webui/templates/panel_birthdays_celebrations.html", "(none)", "Retire the Panels templates"),
    ("api/webui/templates/panel_bobcat_hour.html", "(none)", "Retire the Panels templates"),
    ("api/webui/templates/panel_learning_objective.html", "(none)", "Retire the Panels templates"),
    ("api/webui/templates/panel_missing_work.html", "(none)", "Retire the Panels templates"),
    ("api/webui/templates/panel_random_student_no_repeats.html", "(none)", "Retire the Panels templates"),
    ("api/webui/templates/panel_random_student.html", "(none)", "Retire the Panels templates"),
    ("api/webui/templates/panel_sports_results.html", "(none)", "Retire the Panels templates"),
    ("api/webui/templates/panel_upcoming_events.html", "(none)", "Retire the Panels templates"),
    ("api/webui/templates/panel_whats_due.html", "(none)", "Retire the Panels templates"),
    ("api/webui/static/panels/panel.css", "(none)", "Retire the Panels responsive kit"),
    ("api/webui/static/panels/panel.js", "(none)", "Retire the Panels responsive kit"),
    ("api/webui/static/panels/themes.css", "(none)", "Retire the Panels responsive kit"),
    ("api/webui/static/pages/panels.css", "(none)", "Retire the Panels console assets"),
    ("api/webui/static/pages/panels_clipboard.js", "(none)", "Retire the Panels console assets"),
    ("api/webui/static/scratch/_harness.html", "(none)", "Retire obsolete Panel scratch pages"),
    ("api/webui/static/scratch/agenda.html", "(none)", "Retire obsolete Panel scratch pages"),
    ("api/webui/static/scratch/departures.html", "(none)", "Retire obsolete Panel scratch pages"),
    ("api/webui/static/scratch/events.html", "(none)", "Retire obsolete Panel scratch pages"),
    ("api/webui/static/scratch/missing.html", "(none)", "Retire obsolete Panel scratch pages"),
    ("api/tests/panels/__init__.py", "(none)", "Retire the Panels tests"),
    ("api/tests/panels/panels_clipboard.test.mjs", "(none)", "Retire the Panels tests"),
    ("api/tests/panels/test_panels_js.py", "(none)", "Retire the Panels tests"),
    ("api/tests/panels/whats_due_boundary.test.mjs", "(none)", "Retire the Panels tests"),
    ("api/tests/webui/routes/test_panels.py", "(none)", "Retire the Panels tests"),
    ("api/tests/webui/test_panel_data.py", "(none)", "Retire the Panels tests"),
    ("docs/reference/panels-route-card.md", "(none)", "Retire the Panels route card"),
    ("api/webui/deck_schedule.py", "(none)", "Rename the schedule resolver to day_schedule"),
    ("api/tests/test_deck_schedule.py", "(none)", "Rename the schedule resolver tests to day_schedule"),
    ("docs/handoffs/smartdeck-slice1-schedules.md", "(none)", "old-lineage only; completed slice handoff"),
    ("docs/handoffs/smartdeck-slice2-contract-and-writes.md", "(none)", "old-lineage only; completed slice handoff"),
    ("docs/handoffs/smartdeck-slice3-management-ui.md", "(none)", "old-lineage only; completed slice handoff"),
    ("docs/handoffs/smartdeck-slice4-display-and-timer.md", "(none)", "old-lineage only; completed slice handoff"),
    ("engine/dev/test_cases/test_orchestrator_manual.py", "(none)", "orphaned by a405b24; imported the retired engine.orchestrator"),
    ("engine/orchestrator.py", "a405b24", "cruft-removal audit: retire dead code"),
    ("engine/packagers/note_handler.py", "926b4f2", "Modularize live-fire workflows"),
    ("engine/rendering/physical/note_adapter.py", "926b4f2", "Modularize live-fire workflows"),
    ("engine/rendering/physical/note_spike.py", "926b4f2", "Modularize live-fire workflows"),
    ("engine/rendering/physical/templates/note.html.j2", "926b4f2", "Modularize live-fire workflows"),
    ("engine/tests/integration/test_backwards_compatibility.py", "a405b24", "cruft-removal audit: retire dead code"),
    ("engine/tests/integration/test_orchestrator.py", "a405b24", "cruft-removal audit: retire dead code"),
    ("engine/tests/unit/test_noteforge_cornell.py", "926b4f2", "Modularize live-fire workflows"),
    ("engine/tests/unit/test_noteforge_frayer.py", "926b4f2", "Modularize live-fire workflows"),
    ("engine/tests/unit/test_noteforge_guided_cloze.py", "926b4f2", "Modularize live-fire workflows"),
    ("engine/tests/unit/test_noteforge_live_handler.py", "926b4f2", "Modularize live-fire workflows"),
    ("api/webui/school_calendar.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/bell_schedule.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/day_schedule.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/calendar_csv.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/schedule_setup.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/schooldays.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/routes/calendar.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/routes/schedule.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/routes/gradebook_sweep.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/routes/gradebook_extensions.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/routes/gradebook.py", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/webui/routes/gradebook_common.py", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/webui/routes/gradebook_policy.py", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/webui/routes/gradebook_extra_time.py", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/webui/routes/gradebook_snapshot.py", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/webui/templates/gradebook.html", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/webui/static/gradebook.js", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/webui/static/gradebook", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/webui/static/pages/gradebook.css", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/tests/test_gradebook_routes.py", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/tests/test_gradebook_policy_routes.py", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/tests/webui/routes/test_gradebook_extra_time.py", "(none)", "Retire the unlinked Gradebook console page; grading lives in Canvas Live and MCP"),
    ("api/operation_ledger/adapters/sweep.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/work_registry/providers/late_work.py", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/static/pages/calendar.js", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/static/pages/calendar.css", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/static/gradebook/sweep.js", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/webui/templates/calendar.html", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/default_docs/AI Authoring/Author an Academic Calendar.txt", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("docs/contracts/canonical-school-calendar-contract.md", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/diagnose_newquizzes.py", "(none)", "Retire the hand-run New Quizzes auth diagnostic"),
    ("api/scripts/probe_newquizzes_auth.py", "(none)", "Retire the hand-run New Quizzes auth diagnostic"),
    ("api/powergrader/estimates.py", "(none)", "Retire the never-wired PowerGrader estimate helpers"),
    ("api/webui/static/gradebook/extensions.js", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/default_docs/AI Authoring/Author a Class Schedule.txt", "(none)", "Retire the school calendar, bell schedules, and the late-work sweep"),
    ("api/tests/test_reports_routes.py", "(none)", "Retire GET /api/assignments-full; its last browser consumer went with the extension UI"),
    ("api/webui/routes/gradebook_curves.py", "(none)", "Retire the console curve controls in favor of the reviewed MCP grade-adjustment lane"),
    ("api/webui/static/gradebook/curves.js", "(none)", "Retire the console curve controls in favor of the reviewed MCP grade-adjustment lane"),
    ("api/webui/gradebook_service.py", "(none)", "Retire the curve-event store after moving grade adjustment math to the shared service"),
    ("api/tests/test_curve_event_storage.py", "(none)", "Retire the curve-event store and its storage tests"),
    ("api/powergrader/packet.py", "(none)", "Consistent scoring feedback: no persona, one rendered layout; only tests imported it"),
    ("api/powergrader/copilot_packet.py", "(none)", "Consistent scoring feedback: no persona, one rendered layout; only tests imported it"),
    ("api/powergrader/copilot_packet_support.py", "(none)", "Consistent scoring feedback: no persona, one rendered layout; only tests imported it"),
    ("api/tests/powergrader/test_copilot_packet.py", "(none)", "Consistent scoring feedback: retired module, retired test"),
    ("api/webui/routes/feedback.py", "(none)", "Consistent scoring feedback: personas removed entirely, /api/feedback/* is gone"),
    ("api/webui/routes/feedback_library.py", "(none)", "Consistent scoring feedback: personas removed entirely, /api/feedback/* is gone"),
    ("api/tests/webui/routes/test_feedback_library.py", "(none)", "Consistent scoring feedback: retired persona route, retired test"),
    ("api/default_docs/Feedback Contracts/Glows & Grows (Basic).md", "(none)", "Consistent scoring feedback: base shape is product-owned Python text, not a seeded workspace file"),
    ("api/missing_sweep.py", "(none)", "Retire the Canvas Expert missing-work sweep; Canvas owns its missing-submission policy"),
    ("api/operation_ledger/adapters/missing_fill.py", "(none)", "Retire the Canvas Expert missing-work sweep; Canvas owns its missing-submission policy"),
    ("api/tests/test_missing_sweep.py", "(none)", "Retire the Canvas Expert missing-work sweep and its tests"),
    ("api/tests/test_missing_sweep_operation.py", "(none)", "Retire the Canvas Expert missing-work sweep and its tests"),
    ("api/routine_runtime.py", "(none)", "Retire scheduled routines; the host agent owns recurring work"),
    ("api/routine_reads.py", "(none)", "Retire scheduled routines; the host agent owns recurring work"),
    ("api/webui/routine_coordinator.py", "(none)", "Retire scheduled routines; the host agent owns recurring work"),
    ("api/custom_routines", "(none)", "Retire scheduled routines and the custom Python loader"),
    ("api/webui/routes/routines.py", "(none)", "Retire the routines control page and endpoints"),
    ("api/webui/templates/routines.html", "(none)", "Retire the routines control page"),
    ("api/webui/templates/_routines_panel.html", "(none)", "Retire the routines home panel"),
    ("api/dailywriting", "(none)", "Retire private writing-history records"),
    ("api/webui/routes/dailywriting.py", "(none)", "Retire private writing-history routes"),
    ("api/learning_objectives.py", "(none)", "Retire the separate learning-objectives workflow"),
    ("api/default_docs/AI Authoring/Author a Learning Objective.txt", "(none)", "Retire the separate learning-objectives workflow"),
    ("api/tests/test_durable_identity_invariant.py", "(none)", "Retire the Writing Record identity invariant with its storage feature"),
    ("api/pseudonym_rename.py", "(none)", "Pseudonym assignments are permanent"),
    ("api/powergrader/oral_reading.py", "(none)", "Retire the unsupported oral-reading scoring branch"),
    ("api/powergrader/blind_first.py", "(none)", "Retire the unused blind-first review mode"),
    ("api/webui/mirror_reads.py", "(none)", "Retire duplicate mirror read wrappers"),
    ("api/webui/profiles.py", "(none)", "Retire unused profile persistence module"),
    ("engine/rendering/canvas", "(none)", "Retire unused Canvas package export chain"),
    ("engine/validation/validator.py", "(none)", "Retire unused offline validation chain"),
    ("engine/validation/rules", "(none)", "Retire unused validation rules"),
    ("engine/validation/fixers", "(none)", "Retire unused validation fixers"),
    ("engine/parsing/text_parser.py", "(none)", "Retire the legacy plain-text quiz format"),
    ("engine/parsing/parser_protocol.py", "(none)", "Retire the unused text-parser protocol"),
    ("engine/packagers/canvas_handler.py", "(none)", "Retire unused Canvas package export chain"),
    ("engine/packagers/packager.py", "(none)", "Retire unused Canvas package export chain"),
    ("docs/contracts/oral-reading-evidence-contract.md", "(none)", "Retire oral-reading evidence contract"),
    ("docs/reference/writing-record-module-map.md", "(none)", "Retire writing-record module reference"),
    ("docs/guides/canvasexpert-agent-capabilities.md", "(none)", "START HERE and MCP guide are the current agent capability references"),
    ("docs/guides/cs-project-authoring.md", "(none)", "Retire the superseded CS project authoring guide"),
    ("docs/mcp-capability-probe-brief.md", "(none)", "Retire the completed MCP capability probe brief"),
    ("docs/reference/authoring-contract-drift.md", "(none)", "Move the remaining Accelerate finding into the current differentiation reference"),
    ("docs/reference/operation-ledger-design.md", "(none)", "Merge operation-ledger design into its current module map"),
    ("docs/guides/Holidays.csv", "(none)", "Keep calendar defaults in one canonical source"),
)


def _contains_retired_product_content(path: Path) -> bool:
    """Ignore interpreter caches left by running tests in retired packages."""
    if path.is_file():
        return True
    if not path.is_dir():
        return False
    for child in path.iterdir():
        if child.name == "__pycache__":
            continue
        if _contains_retired_product_content(child):
            return True
    return False


def test_retired_paths_are_absent():
    present = []
    for relative, retired_by, subject in RETIRED_PATHS:
        if _contains_retired_product_content(REPO_ROOT / relative):
            origin = (
                f"retired by {retired_by}"
                if retired_by != "(none)"
                else "old-lineage only (no retirement commit)"
            )
            present.append(f"{relative}: present; {origin}; {subject}")

    assert not present, (
        "These paths were deleted on purpose and are back:\n"
        + "\n".join(present)
        + "\nIf this is an intentional revival, delete the row for it in RETIRED_PATHS. "
        "If not, it is probably an old-lineage merge."
    )
