"""Load-bearing laws for the private, metadata-only Writing Timeline evidence."""
import json

import pytest

from api.powergrader import writing_timeline


@pytest.mark.parametrize(
    ("submission_types", "allowed_extensions", "expected"),
    [
        (["online_upload"], ["docx"], True),
        (["ONLINE_UPLOAD"], [".DOCX"], True),
        (["online_upload", "online_text_entry"], ["docx"], False),
        (["online_upload"], ["docx", "pdf"], False),
        (["online_upload"], [], False),
        ([], ["docx"], False),
    ],
)
def test_only_docx_only_uploads_are_tracked(submission_types, allowed_extensions, expected):
    assert writing_timeline.is_tracked_assignment({
        "submission_types": submission_types,
        "allowed_extensions": allowed_extensions,
    }) is expected


def test_safe_projection_never_exposes_raw_office_identity_or_per_block_content(
    _timeline_docx,
):
    raw = writing_timeline.parse_docx(_timeline_docx(
        blocks=[("insertion", "fictional writing", "Fictional Learner")],
        creator="Fictional Learner", last_modified="Private Workstation",
    ))
    private = writing_timeline.categorize_authors(
        raw, submission_canvas_id="u-1",
        roster=[{"canvas_id": "u-1", "name": "Fictional Learner"}],
    )

    safe = writing_timeline.safe_projection(private)
    serialized = json.dumps(safe)

    assert safe["available"] is True
    assert safe["largest_insertions"][0]["author_category"] == "submission_author"
    assert "Fictional Learner" not in serialized
    assert "Private Workstation" not in serialized
    assert "fictional writing" not in serialized
    assert "blocks" not in safe


@pytest.mark.parametrize("observation", [
    "The learner likely plagiarized the response.",
    "This was probably generated by ChatGPT.",
    "Recommend an academic-integrity referral.",
])
def test_integrity_conclusions_are_replaced_by_a_fixed_notice(observation):
    assert writing_timeline.sanitize_process_observation(observation) == \
        writing_timeline.OBSERVATION_WITHHELD_NOTICE


def test_process_observation_keeps_bounded_neutral_evidence():
    value = "The document contains revision activity across several timestamps."
    assert writing_timeline.sanitize_process_observation(value) == value


@pytest.mark.parametrize(("raw", "expected"), [
    ("2026-07-26T23:04:00Z", "2026-07-26T18:04:00-05:00"),
    ("2026-01-15T18:00:00Z", "2026-01-15T12:00:00-06:00"),
    ("2026-03-08T08:30:00Z", "2026-03-08T03:30:00-05:00"),
    ("garbage", None),
])
def test_timestamps_normalize_to_central(raw, expected):
    assert writing_timeline._normalize_timestamp(raw) == expected
